version: "3.8"
services:
  mongonex:
    image: mongo
    restart: always
    networks:
      - hardhome-network
    volumes:
      - "./mongodata:/data/db"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - hardhome-network
    depends_on:
      - mongonex  
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongonex:27017/

  backend-service:
    build:
      context: hardhome-backend/
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${BACKEND_SERVER_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_HOST: mongonex
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
    image: hardhome-backend-service-image:latest
    restart: on-failure
    # ports:
    #   - 3010:3010
    networks:
      - hardhome-network
    depends_on:
      - mongonex  
    volumes:
      # - hardhome_assets:/usr/src/app/assets
      - ./hardhome-backend:/usr/src/app
    command: npm run nodemon

  api-service:
    build:
      context: hardhome-api/
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${API_SERVER_PORT}
      BACKEND_SERVER_HOST: backend-service
      BACKEND_SERVER_PORT: ${BACKEND_SERVER_PORT}
    image: hardhome-api-service-image:latest
    restart: on-failure
    ports:
      - 3020:3020
    networks:
      - hardhome-network
    volumes:
      - ./hardhome-api:/usr/src/app
    command: npm run nodemon  

  frontend-service:
    build:
      context: hardhome-frontend/
      dockerfile: Dockerfile.dev
    container_name: hardhome-frontend-service-prod
    volumes:
      - "./envfile:/usr/share/nginx/html/envfile"
    ports:
      - "12000:80"
    restart: on-failure   

networks:
  hardhome-network:
    name: hardhome-docker-network
    driver: bridge