version: "3.8"
services:
  hardhome-frontend:
    build:
      context: hardhome-frontend/
      dockerfile: Dockerfile.dev
    # image: 121487958432.dkr.ecr.us-east-1.amazonaws.com/hardhome-web-server-image-prod:latest
    container_name: hardhome-frontend
    volumes:
      - "./envfile:/usr/share/nginx/html/envfile"
    ports:
      - "12000:80"
    restart: on-failure  