apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: hardhome-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardhome-frontend-app
  template:
    metadata:
      labels:
        name: hardhome-frontend-pod
        app: hardhome-frontend-app
    spec:
      containers:
        - name: hardhome-frontend-container
          image: 342511920901.dkr.ecr.us-east-1.amazonaws.com/hardhome-frontend-service-image-prod:latest     
          ports:
            - containerPort: 80
          volumeMounts:
            - name: envfile-config
              mountPath: /usr/share/nginx/html/env         
      volumes: 
        - name: envfile-config
          configMap:
            name: hardhome-frontend-configmap    
      imagePullSecrets:
        - name: us-east-1-ecr-registry  
