apiVersion: v1
kind: Service
metadata:
  name: hardhome-frontend-service
spec:
  type: NodePort
  selector:
    app: hardhome-frontend-app
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008