apiVersion: v1
kind: Service
metadata:
  name: hardhome-mongo-service
  labels:
    app: hardhome-mongo-service
spec:
  ports:
  - port: 27017
    name: mongodbport
  clusterIP: None
  selector:
    app: hardhome-mongodb